(()=>{
 const KEY='sail-v22-gfx';
 const defaults={quality:3,resolution:1,terrain:true,buildings:true,atmosphere:true,hdr:true,shadows:false,imagery:'arcgis'};
 function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {...defaults}}}
 function save(s){try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}}
 function apply(C,v,s){
  v.resolutionScale=Math.max(.55,Math.min(1.5,+s.resolution||1));
  v.scene.globe.maximumScreenSpaceError=[10,6,3,1.7][Math.max(0,Math.min(3,(+s.quality||3)-1))];
  v.scene.fog.enabled=!!s.atmosphere;v.scene.fog.density=s.atmosphere?.000035:0;
  v.scene.highDynamicRange=!!s.hdr;v.scene.globe.enableLighting=!!s.atmosphere;
  v.shadows=!!s.shadows;v.scene.shadowMap.enabled=!!s.shadows;
  v.__v21BuildingsEnabled=!!s.buildings;
  if(s.terrain===false && !(v.terrainProvider instanceof C.EllipsoidTerrainProvider))v.terrainProvider=new C.EllipsoidTerrainProvider();
 }
 function ui(C,v){if(v.__gfxV22)return;v.__gfxV22=true;const s=load();apply(C,v,s);
  const st=document.createElement('style');st.textContent=`#gfx22btn{position:fixed;z-index:95;right:16px;bottom:145px;background:#071625e8;color:#fff;border:1px solid #ffffff33;border-radius:10px;padding:9px 12px;font:700 11px system-ui;cursor:pointer}#gfx22{position:fixed;z-index:100;right:16px;bottom:190px;width:290px;max-height:70vh;overflow:auto;background:#071625f5;color:#fff;border:1px solid #ffffff35;border-radius:14px;padding:13px;box-shadow:0 16px 45px #0008;font:12px system-ui;display:none}#gfx22.open{display:block}#gfx22 h3{margin:0 0 10px;font-size:13px}#gfx22 .r{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:9px 0}#gfx22 input[type=range]{width:150px}#gfx22 select{background:#0e2538;color:#fff;border:1px solid #ffffff2e;border-radius:7px;padding:5px}#gfx22 button{background:#163b57;color:#fff;border:0;border-radius:8px;padding:7px 9px;cursor:pointer}#gfx22 small{opacity:.67;display:block;line-height:1.35}`;document.head.appendChild(st);
  const b=document.createElement('button');b.id='gfx22btn';b.textContent='⚙ GRAFIK';document.body.appendChild(b);
  const p=document.createElement('div');p.id='gfx22';p.innerHTML=`<h3>V22 · GRAFIK & STREAMING</h3><div class=r><span>Qualität</span><input id=gq type=range min=1 max=4 step=1></div><div class=r><span>Renderauflösung</span><input id=gr type=range min=.6 max=1.35 step=.05></div><div class=r><span>3D-Gebäude</span><input id=gb type=checkbox></div><div class=r><span>Terrain</span><input id=gt type=checkbox></div><div class=r><span>Atmosphäre/Fog</span><input id=ga type=checkbox></div><div class=r><span>HDR</span><input id=gh type=checkbox></div><div class=r><span>Schatten</span><input id=gs type=checkbox></div><div class=r><span>Basiskarte</span><select id=gi><option value=arcgis>ArcGIS Satellit</option><option value=osm>OpenStreetMap</option></select></div><small>Gebäude und Fotomeshes werden weiterhin entfernungsabhängig gestreamt. Höhere Qualität senkt den Terrain-LOD-Fehler, kostet aber GPU/Netzwerk.</small><div class=r><button id=greset>Standard</button><button id=gclose>Schließen</button></div>`;document.body.appendChild(p);
  const $=id=>p.querySelector('#'+id),sync=()=>{$('gq').value=s.quality;$('gr').value=s.resolution;$('gb').checked=s.buildings;$('gt').checked=s.terrain;$('ga').checked=s.atmosphere;$('gh').checked=s.hdr;$('gs').checked=s.shadows;$('gi').value=s.imagery};sync();
  function changed(){s.quality=+$('gq').value;s.resolution=+$('gr').value;s.buildings=$('gb').checked;s.terrain=$('gt').checked;s.atmosphere=$('ga').checked;s.hdr=$('gh').checked;s.shadows=$('gs').checked;s.imagery=$('gi').value;save(s);apply(C,v,s);if(s.imagery!==v.__gfxImagery){v.__gfxImagery=s.imagery;try{v.imageryLayers.removeAll();if(s.imagery==='osm')v.imageryLayers.addImageryProvider(new C.OpenStreetMapImageryProvider({url:'https://tile.openstreetmap.org/'}));else C.ArcGisMapServerImageryProvider.fromUrl('https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer').then(x=>v.imageryLayers.addImageryProvider(x)).catch(()=>{})}catch(e){console.warn('[V22 GFX] imagery',e)}}}
  ['gq','gr','gb','gt','ga','gh','gs','gi'].forEach(id=>$(id).addEventListener('change',changed));$('gq').addEventListener('input',changed);$('gr').addEventListener('input',changed);
  b.onclick=()=>p.classList.toggle('open');$('gclose').onclick=()=>p.classList.remove('open');$('greset').onclick=()=>{Object.assign(s,defaults);sync();changed()};changed();
 }
 function hook(){if(!window.Cesium||!Cesium.Viewer)return setTimeout(hook,40);if(Cesium.Viewer.__gfx22hook)return;const O=Cesium.Viewer;Cesium.Viewer=new Proxy(O,{construct(t,a,n){const v=Reflect.construct(t,a,n);setTimeout(()=>ui(Cesium,v),250);return v}});Cesium.Viewer.__gfx22hook=true}hook();
})();